version: '3.9'

services:
  mariadb:
    image: mariadb
    hostname: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: api
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpwd
    restart: always
    ports:
      - "0.0.0.0:3306:3306"
  phpmyadmin:
    container_name: pma
    image: phpmyadmin:latest
    environment:
      PMA_HOST: "mariadb"
      UPLOAD_LIMIT: 500000K
    ports:
      - '8080:80'
